-- ============================================================================
-- Migration: 007_floating_life_seed
-- Description: Seed data for "浮生记" emotional stories (CLEARED)
-- Created: 2026-05-07
-- Note: All seed stories have been removed. Re-populate with high-quality content.
-- ============================================================================
