-- ============================================================================
-- Migration: 009_floating_life_modern_2
-- Description: 现代言情情感故事 6-10 (CLEARED)
-- Created: 2026-05-07
-- Note: All seed stories have been removed. Re-populate with high-quality content.
-- ============================================================================
